name: Build EXE and APP

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发构建
  workflow_dispatch:  # 允许手动触发

jobs:
  build_windows:
    runs-on: windows-latest  # 使用 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖

    - name: Install PyInstaller
      run: pip install pyinstaller  # 安装 PyInstaller

    - name: Build EXE for Windows
      run: pyinstaller --onefile --hidden-import pynput --hidden-import pyperclip --noconsole auto_input_tool.py

    - name: Upload Windows EXE artifact
      uses: actions/upload-artifact@v4  # 升级到 v4 版本
      with:
        name: auto-input-tool-exe
        path: dist/auto_input_tool.exe  # 上传生成的 EXE 文件

  build_macos:
    runs-on: macos-latest  # 使用 macOS 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装依赖

    - name: Install PyInstaller
      run: pip install pyinstaller  # 安装 PyInstaller

    - name: Build APP for macOS
      run: pyinstaller --onefile --hidden-import pynput --hidden-import pyperclip --windowed auto_input_tool.py

    - name: Upload macOS APP artifact
      uses: actions/upload-artifact@v4  # 升级到 v4 版本
      with:
        name: auto-input-tool-app
        path: dist/auto_input_tool.app  # 上传生成的 macOS APP 文件
